/** Single-token titles that are ordinary English / production language. */
export const COMMON_WORDS = new Set([
  'a','an','the','and','or','of','to','in','on','for','with','by','from','at','as','is','it',
  'be','this','that','these','those','you','your','we','our','they','their','he','she','his',
  'her','my','me','i','not','no','yes','up','down','out','off','over','under','into','about',
  'after','before','again','once','if','then','than','so','too','very','just','only','also',
  'can','will','would','could','should','may','might','must','do','did','done','have','has',
  'had','was','were','are','been','being','get','got','make','made','let','put','take','go',
  'come','see','look','know','think','want','need','like','love','hate','feel','live','play',
  'run','walk','talk','sing','song','songs','track','tracks','album','albums','music','band',
  'artist','artists','sound','sounds','style','voice','vocal','vocals','remix','mix','edit',
  'intro','outro','interlude','untitled','bonus','hidden','instrumental','acoustic','live',
  'demo','version','radio','single','ep','lp','vol','volume','part','pt','feat','featuring',
  'versus','vs','ost','theme','score','soundtrack','original','motion','picture','cast',
  'one','two','three','four','five','six','seven','eight','nine','ten','zero','first','last',
  'new','old','good','bad','best','great','greatest','hits','hit','hot','cold','warm','cool',
  'dark','light','black','white','red','blue','green','gold','silver','pink','yellow','orange',
  'home','house','girl','boy','man','men','woman','women','baby','child','kids','people',
  'world','life','death','time','day','night','today','tomorrow','yesterday','year','years',
  'heart','soul','mind','body','eyes','hands','head','face','blood','fire','water','rain',
  'sun','moon','star','stars','sky','sea','ocean','river','road','street','city','town',
  'dream','dreams','hope','pain','tears','smile','kiss','hold','stay','wait','leave','gone',
  'away','back','here','there','now','then','always','never','forever','still','more','less',
  'all','some','any','every','each','other','another','same','own','such','what','when',
  'where','who','why','how','which','because','while','until','without','through','between',
  'hello','goodbye','sorry','please','thanks','thank','hey','hi','yo','ok','okay','yeah',
  'free','real','true','right','left','high','low','long','short','big','small','little',
  'young','happy','sad','lonely','crazy','beautiful','pretty','sweet','wild','easy','hard',
  'change','start','stop','begin','end','open','close','rise','fall','fly','dance','move',
  'work','works','working','call','called','name','names','number','numbers','thing','things',
  'something','nothing','everything','someone','everyone','nobody','anybody',
  'introducing','untitled','unknown','various','artist','compilation','karaoke','tribute',
  'cover','covers','session','sessions','anthology','collection','deluxe','remaster','remastered',
  'expanded','edition','reissue','live','unplugged','acoustic','instrumental',
  'game','games','show','shows','movie','movies','film','films','series','season','episode',
  'character','logo','brand','official','trailer','teaser','clip','scene','shot',
  'pop','rock','jazz','folk','soul','funk','punk','metal','rap','trap','house','techno',
  'ambient','classical','country','blues','disco','gospel','indie','edm','lofi',
  'happy','birthday','christmas','halloween','wedding','funeral',
  'test','unknown','none','null','n/a','na','tba','tbd','misc','other','self',
  'dusty','rusty','shiny','empty','late','early','raw','clean','dirty','fast',
  'slow','deep','wide','thin','thick','sharp','flat','fresh','modern','simple',
  'perfect','broken','lost','hidden','secret','quiet','loud','soft','hard',
  'hiss','hymn','hymns','choir','melody','harmony','rhythm','beat','groove',
  'riff','solo','duet','trio','quartet','aria','opus','suite','prelude',
  'air','pad','pads','hiss','click','noise','clip','clipping','buzz','hum','tone','tones',
  'inner','outer','upper','lower','super','mega','ultra','mini','max','pale',
  'bright','silent','golden','iron','steel','stone','paper','glass','metal',
  'monday','tuesday','wednesday','thursday','friday','saturday','sunday',
  'january','february','march','april','may','june','july','august','september','october',
  'november','december',
]);

export const SKIP_EXACT = new Set([
  'greatest hits',
  'the best of',
  'best of',
  'live album',
  'untitled',
  'intro',
  'outro',
  'interlude',
  'bonus track',
  'hidden track',
  'track 1',
  'various artists',
  'unknown artist',
  'no artist',
  'traditional',
  'anonymous',
  'soundtrack',
  'original soundtrack',
  'music from the motion picture',
]);

export const SPECIAL_PURPOSE = [
  /^\[.*\]$/,
  /^various artists$/i,
  /^unknown$/i,
  /^untitled$/i,
  /^no artist$/i,
  /^traditional$/i,
  /^anonymous$/i,
  /^language instruction$/i,
  /^disney studio chorus$/i,
];
